### ISSUE TITLE
v 1.11.1 stopped working on macOS 10.15.3

### ISSUE THREAD

**Issue by k2n** [txn2/kubefwd#105]
Hi, 

First thx for such a great tool, it improves our productivity a lot!

We upgraded from v1.9.3 to v1.11.1, and one of my colleagues faced the issue that it stops immediately. Looks like it happens only macOS 10.15.3. It worked fine on 10.15.2, and after I upgraded, I started to see the same issue. The output looks like this;

```
sudo bin/kubefwd svc -n dev-kenji -x arn:aws:eks:us-west-2:a_aws_account_id:cluster/parkside-dev
INFO[09:43:42]  _          _           __             _
INFO[09:43:42] | | ___   _| |__   ___ / _|_      ____| |
INFO[09:43:42] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
INFO[09:43:42] |   <| |_| | |_) |  __/  _|\ V  V / (_| |
INFO[09:43:42] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
INFO[09:43:42]
INFO[09:43:42] Version 1.11.1
INFO[09:43:42] https://github.com/txn2/kubefwd
INFO[09:43:42]
INFO[09:43:42] Press [Ctrl-C] to stop forwarding.
INFO[09:43:42] 'cat /etc/hosts' to see all host entries.
INFO[09:43:42] Loaded hosts file /etc/hosts
INFO[09:43:42] Hostfile management: Original hosts backup already exists at /Users/kenji/hosts.original
WARN[09:43:44] WARNING: No Running Pods returned for service market-data-gateway in dev-kenji on cluster .
INFO[09:43:44] Done...
```
I verified v 1.10.0 worked on macOS 10.15.3. Is there any way to output verbose info helpful to debug? I turned on Firewall, but `kubefwd` is included in the whitelist and allowing incoming connections in macOS's Security & Privacy.

**Comment by k2n** [comment]
I noticed if I switch between `v1.10.0` and `v1.11.1` back and forth, `v1.11.1` starts to work. However, I got the same issue after rebooting my machine.

**Comment by calmkart** [comment]
@k2n 
I checked the code and this issue may not be related to the system version.
I found that there is a bug in the current service monitoring code. When there is a podless service in a namspace to be monitored, if this service is just discovered first, kubefwd may have no time to wait for other pod services and directly end the main program. (Because waitgroup does not have +1, done is directly done in the main program).
But if the service without pod in service discovery is found after other services, there should not be this problem. (But the order of service discovery may be random)
I think adding a delay when finding no pod return in the service can solve this bug, but this may not be the best solution.
I will do a fix later. We can check if this is the cause. I think it is most likely caused by this bug.

**Comment by k2n** [comment]
Hi @calmkart Is there a way for me to test your fix, or would you create a release? Thx!

**Comment by calmkart** [comment]
`git clone https://github.com/calmkart/kubefwd`
and
`sudo -E go run cmd/kubefwd/kubefwd.go svc`
@k2n

**Comment by k2n** [comment]
Tested 0.12.0 and seems to be fixed. I'll push the version and have my colleagues use it. Will report if we still see the issue, but close this for now. Thx!
