### ISSUE TITLE
there are easier ways to do this

### ISSUE THREAD

**Issue by sokoow** [txn2/kubefwd#11]
Hey, neat tool and nice idea, but I think that for some aspects of it, like testing frontends, using traefik might simplify it a lot - it just looks at the host header and forwards to a common ingestion point (like all reverse proxies do). So instead of port fwd, you to throw it a service name, port, subdomain in a manifest, and then add the subdomain as 127.0.0.1 in /etc/hosts - one of examples is here: https://github.com/sokoow/kube-desktop/blob/master/ingress/dashboard-ingress.yaml

Let me know what you think.

**Comment by cjimti** [comment]
I would not use this for simply testing frontends, no real reason to do so since they are already exposed to the public. kubefwd was built to support port forwarding services that do not and sometimes should not ever be exposed to public ingress, most microservices for instance. 

This is just a developer tool. The example you link to is an Ingress configuration, which is a proper way to bring in public traffic to your endpoint.

Thanks for your input. I hope my explanation made sense.

**Comment by atombender** [comment]
@sokoow There are lots of things that aren't HTTP(S). Databases, for example.
