### ISSUE TITLE
Getting forwarded an evicted pod instead of running one

### ISSUE THREAD

**Issue by dantheman999301** [txn2/kubefwd#125]
Version 1.14.0
---

I use the following command:
```
kubefwd svc -n production -l "app.kubernetes.io/app in (app1, app2, app3)"
```

I recently noticed that if one of those services has a pod that is evicted and one that is running, `kubefwd` will forward me the evicted one instead of the active one.

Some output when running:
`INFO[14:51:58] Port-Forward: tenant-reporting:80 to pod tenant-reporting-65d64b779c-hndh5:80`

Compared to the output of `kubectl get pods`:

```
tenant-reporting-65d64b779c-hndh5                                 0/1     Evicted     0          3d23h
tenant-reporting-cfc584774-hccxn                                  0/1     Evicted     0          3d
tenant-reporting-cfc584774-lj9vf                                  1/1     Running     0          94m
```

EDIT: In case it helps, when looking up the pods that were marked as `Evicted` I had to look them up by `--field-selector=status.phase=Failed`.

`--field-selector=status.phase=Evicted` for some reason didn't work.

**Comment by mhindery** [comment]
I have added a filtering of these pods in the pull request https://github.com/txn2/kubefwd/pull/126. Since that PR already makes some changes in the structure, I didn't do a separate PR on master as I'd rather get the PR through and not duplicate the work.

Should this be a blocking issue for you, I have currently 3 PR's open against this repo, and in order to start using that new code in our developments already until the PR's are merged, I have merged these PR's into a branch on my forked repo and compiled them into a release with binaries for mac and linux. You could use that one https://github.com/mhindery/kubefwd/releases/tag/OTA-dev-01

**Comment by cjimti** [comment]
I have not had time to sort out what went wrong with the parallelization you did, however it produced duplicates for many of my services in the the /etc/hosts . It also broke `kubefwd` for a few others. Until I or someone else can write tests, I need to spend longer in manual testing. `kubefwd` is not perfect but a lot of people rely on it, and I need to be more careful about releasing changes that could break it.

**Comment by cjimti** [comment]
@dantheman999301  I reverted the breaking changes in 1.14.0, are you still having this issue in 1.14.1?

**Comment by dantheman999301** [comment]
@cjimti I'll update and let you know. Hopefully an evicted pod will show up for me to test with.

**Comment by dantheman999301** [comment]
I don't think I've seen this since updating, feel free to close this.
