### ISSUE TITLE
Support helm charts

### ISSUE THREAD

**Issue by planetf1** [txn2/kubefwd#14]
Helm is becoming increasingly used for deployment of kubernetes resources that might represent an 'application'

It would be cool if kubefwd became helm aware (or has a twin helmfwd! ) whereby it would enumerate the services that are part of the helm chart, and do kubefwd on each.

(not used kubefwd yet... next... but an initial idea)

**Comment by sgandon** [comment]
I am not sure what you mean by being helm chart aware, cause this tool enumerates the services that are deployed on the cluster to forward them locally.
So if you services are deployed with helm just like mine, then you'll be able to forward them the same way.
Helm is a package manager to deploy resources, but kubefwd is just a runtime tool to map K8 services locally.
I am not sure to see relation.

**Comment by planetf1** [comment]
My bad for not explaining thoroughly..

When I initially looked I thought the service name was passed. Now I realise it is forwarding the ports for all services within the selected namespace.

One alternative would be to only forward for resources for a specified helm chart -- I for example tend to have a few different helm charts deployed within the same namespace. Sometimes they have overlapping ports, and I just want to work with one at a time. Using multiple namespaces myself would avoid the need for this, but sometimes that seperation is harder than needed.

Hope that explains my thought, though it was just that, not essential, and great idea on the tool as a whole...

**Comment by cjimti** [comment]
@planetf1 you can use a selector to limit the services returned `-l key1=value1,key2=value2`, or for some helm chart it would likely be `-l helm.sh/chart=NAME-VERSION`. 

You can also forward multiple namespaces with additional `-n` flags, the first is primary and can be accessed with the short name or full cluster name the rest will be full cluster name due to overlaps.

**Example:**
`sudo kubefwd services -n rook-ceph -n monitoring`

A full cluster name would be something like:
`prometheus-k8s.monitoring.svc.cluster.local:9090`

**Comment by cjimti** [comment]
@planetf1 I'd like to make kubefwd as useful as possible. If my explanation above does not help you in forwarding your helm based deployment let me know so I can add a specific feature to accomplish this. Thanks for taking the time to submit an issue.
