### ISSUE TITLE
Runtime: error copying from remote stream to local connection

### ISSUE THREAD

**Issue by kojuka** [txn2/kubefwd#168]
Hey guys - love kubefwd.  In fact it's become the secret for staying sane while developing microservices in a kubernetes world.  Thanks for all the hard work.

My issue is related to keeping a connection alive to my kafka service.  I keep getting this issue:
`Runtime: error copying from remote stream to local connection`

The way I can replicate it is by following these steps:

1. start kubefwd to connect to my kafka service
2. start my microservice locally and wait for it to connect to kafka to be able to publish/subscribe to messages
3. publish a message to kakfka
4. restart my microservice (i use nodemon so hitting `rs` restarts the service)

If I follow these steps I always get the error message mentioned above.    Any tips?  Thanks in advance.

**Comment by kojuka** [comment]
If I drop down to kubefwd@1.13.2 the issue goes away.   That will be my work around for now, but I'm still interested in getting to the bottom of this.  Thanks

**Comment by cjimti** [comment]
@kojuka I am happy to hear the kubefwd is working out for you. 

Unfortunately, I don't use kubefwd for Kafka since in my experience it provides internal IP addresses for network discovery and not hostnames that would resolve to the kubefwd `/etc/hosts` entries. This might be the problem you are running into. 

I have a special version of `kubefwd` I run that assigns cluster IP addresses in place of 127 addresses. It's not really compatible with features like multi-cluster forwaring and there are a few other downsides, so I have never attempted to bring this feature into a release.

I can put more work into it if you are interested in possibly release it as an experimental feature (assuming this is the problem you are having).
