### ISSUE TITLE
Track down forwarded services

### ISSUE THREAD

**Issue by flupec** [txn2/kubefwd#170]
Hello.
Can you add some mechanism to track down forwarded services in kubefwd? Event dispatch or something.
My team could access the port-forwarded services, but now it's impossible due to unexported variables. We use your project as a go module.
Or can i make a PR to implement such mechanism?

**Comment by flupec** [comment]
This request is due to the following - some environments have a kubelet parameter --streaming-connection-idle-timeout duration equal to a small value. My team suffers from the fact that on some environments, connections are dropped. 

At the moment we are using our extension, in which we reopen connections after dropping, but this behavior is possible only in version 1.13 and below.

**Comment by cjimti** [comment]
@flupec interesting, I did not know about `--streaming-connection-idle-timeout`, this could account for a few complaints about constant connection dropping. I don't have that arg set on any of my kubelets.

There have been attempts to add re-connection code but it has always caused more problems than it solved. It's very difficult to determine if a connection goes down without actively polling it, and if the loss is temporary then an attempt to automatically re-connect may actually be worse. 

Re: "due to unexported variables", while `kubefwd` was never meant to be used as a module, I am not at all against it. Kubefwd is very stable in the way my team and I use it. I am open to changes that don't disrupt that. What would you like exposed? 

This project is also very immature in terms of tests and proper documentation. It was originally a weekend project to solve one specific development problems.

**Comment by flupec** [comment]
@cjimti I made a PR. This approach works as expected But i wonder if we need to add an option to change stream connection period creation.
[PR](https://github.com/txn2/kubefwd/pull/171)
