### ISSUE TITLE
Specify service name explicitly without using Selector

### ISSUE THREAD

**Issue by roylee17** [txn2/kubefwd#176]
Is there a way to specify the services explicitly without using Selector?

There are scenarios where even the most specific labels match too many services.
And the service provisioning is beyond our control.

**Comment by cjimti** [comment]
This sounds like a good enhancement.

**Comment by svavassori** [comment]
I'm starting to learn Go in my spare time and I was searching for a relatively small project to play with, so to have a real goal instead of a dummy one. I have a good experience in programming with other languages, so I'm not a newbie that starts with Go, but I'm a newbie _in_ Go.

I recently discovered **kubefwd** and what I was missing is exactly this feature, so I thought it could be a good starting point.
About a possible solution, my first thought was to provide a command line flag that accepts a regex to match all the services' names you want to forward.

@cjimti do you think that it is something reasonable to do considering my Go knowledge or it is too big?

**Comment by cjimti** [comment]
merged in #187
