### ISSUE TITLE
Host file pollution on Windows

### ISSUE THREAD

**Issue by imdbere** [txn2/kubefwd#195]
Hi, first of all thanks for this great tool !
I am using kubefwd on windows and it seems like the host file backup and restore mechanism is not always working correctly. When for example the kubefwd process is not terminated gracefully (e.g. after a crash or a PC shutdown), the host file is not cleaned when kubefwd is started again but keeps some of the previous entries, which results in a corrupt and unusable host file that needs to be cleaned by hand.
Any suggestions for this ?

Thanks 😄

**Comment by cjimti** [comment]
@imdbere The first time `kubefwd` is run it creates a backup (or if no backup exists). It does this in the event that you have a heavily customized `/etc/hosts` and `kubefwd` were cause any problems with it. `kubefwd` does not have any automated  restore ability since it would be difficult to know if a user or other system has made changes that should not be overridden.  To manually restore a backup just copy the `/home/craig/hosts.original` back to `/etc/hosts`, or equivalent location on Windows.

`kubefwd` only adds and removes lines for hosts it is currently forwarding, if Windows crashes and you restart `kubefwd` it would not know that existing entries are from a crash or were added by your or another system intentionally. 

Since `kubefwd` only added entries of host names to loop back IPs, any entries left after a crash would be annoying but should not cause any issues. A few quick ways to clean up in the event of a Windows crash would be to start forwarding the same services again and exit clean, or truncate the `/etc/hosts`, or copy the backup.

It would be a much bigger problem if `kubefwd` unintentionally "cleaned" `/etc/hosts` of entries added by users or other systems. Since `kubefwd` is not the sole manager of your `/etc/hosts` it must error on the side of caution when removing anything.
