### ISSUE TITLE
/etc/hosts not correctly parsed

### ISSUE THREAD

**Issue by atombender** [txn2/kubefwd#20]
```
$ sudo kubefwd services -n development
[...]
Loading hosts file /etc/hosts
Can not load /etc/hosts
2018/11/13 16:52:31 Duplicate hostname entry for trc.taboola.com -> 0.0.0.0

$ grep taboola.com /etc/hosts
#0.0.0.0  cdn.downloaddeft.com trc.taboola.com images.taboola.com b.scorecardresearch.com
#0.0.0.0  aa-gb.mgid.com rs.gwallet.com rp.gwallet.com ads.yahoo.com cdn.taboola.com
#0.0.0.0  trc.taboola.com images.taboola.com cdn.taboola.com c2.taboola.com
```

Notice how the lines are commented out. Kubefwd shouldn't be parsing this as anything.

The fact that it's doing so is a bit disconcerting — anything that messes with `/etc/hosts` had better be really solid so one doesn't lose stuff.

**Comment by cjimti** [comment]
@atombender this is why it backs it up first. I completely understand. 

I'm using a lib called https://github.com/cbednarski/hostess which has a nice API but looks like it's not really maintained anymore. I may need to just write my own.

**Comment by atombender** [comment]
Thanks, makes sense.

**Comment by cjimti** [comment]
@atombender thanks, but your concern is legit. I'm not quite sure what the best approach should be in these (edge?) cases.  hostess has had issues open for over two years so I may just fork it and lightly maintain it under this txn2 org, suppressing features we don't need. 

I'll keep this open and add it to the next milestone since I am sure you are not the only one who has encountered this.

**Comment by atombender** [comment]
We could also fix it. Looks the project isn't fully unmaintained.

**Comment by cjimti** [comment]
I am closing this issue until we can come up with an actionable solution. @atombender thank you for your input and hopefully, we can come up with a better solution.
