### ISSUE TITLE
Reconnect when service or pod is restarted

### ISSUE THREAD

**Issue by mrumpf** [txn2/kubefwd#21]
During development I often restart the pods to apply a new configuration for example. Unfortunately I have to stop kubefwd and start it again to re-establish the connection.
It would be great if there is some cron option to check for changes to the services or pods and restart the connection. Or maybe there is a hook in Kubernetes, where you can be notified of a change in the underlying pod where the connection is going to and the connection could be restarted without having to stop & start kubefwd completely.

For example a "--reconnect" option:
````
sudo kubefwd services --reconnect -n default -c~/.bluemix/plugins/container-service/clusters/my-cluster/kube-config-fra02-mycluster.yml
````

**Comment by cjimti** [comment]
@mrumpf I like the --reconnect option idea, although technically it's not a reconnect since the pod is likely gone forever, I am assuming Kubernetes replaced it. 

kubefwd can detect a communication failure, so adding a `--reconnect` could indicate that you want it to find a new pod to connect to (assuming there is one, available).

**Comment by ostlerc** [comment]
newer versions of kubectl allow port forwarding a service instead of a pod. maybe that would help here?

**Comment by cjimti** [comment]
Actually, it would solve #35, and I am certainly going to take a deeper look at it as soon as I can. 

My concern about applying it to here is that many of us are monitoring or tailing the log of the specific pod being forwarded. I think general service forwarding could be an option for those who don't really care which Pod the backend system is using. This might even be a default with a flag to use Pod selectors. 

Thanks!

**Comment by rjanovski** [comment]
a reconnect on network failure is super important for stability.
in my setting kubefwd lasts minutes at best before failing with `Runtime error: lost connection to pod`; could be my vpn access to aws that keep restarting

forward to service rather to a pod is a huge plus as well for stability. And using a single pod is different from the kubernetes service behavior that one usually expects.

**Comment by JorritSalverda** [comment]
If the tool can watch the k8s api for changes it can immediately pick a new ready pod as soon as the one selected is terminated. Currently this tool has the same shortcoming as `kubectl port-forward` (even if used as a service, because the only thing it uses the service for is to find a pod to connect to, just like this tool). If that can be fixed it's an awesome tool we can have all of our developers start using.

**Comment by cjimti** [comment]
I am closing this in favor of the re-connect proposal in #70. However, I may build on a solution in the future that somehow forwards to services, although I would have hack something together since the Kubernetes API does not support it. It would likely require an in-cluster component (something I've tried to avoid) like telepresence. 

I'll look at the idea of listening for Pod events as a component to #70 since they are somewhat related. Connection timeouts and the Pod going away have the same effect on the end-user and both require finding a pod for (re)connecting.
