### ISSUE TITLE
kubefwd doesn't work for specific ports/hostnames

### ISSUE THREAD

**Issue by kelciocajueiro** [txn2/kubefwd#221]
Hi Team, 

I am using this command to run kubefwd

`sudo kubefwd services -x <context> -n <namespace> -c <kube_file_path> -l "app in (idm, sbb-amq)"`

That is the log

**INFO[14:13:58] Port-Forward:       127.1.27.1 sbb-amq:8161 to pod sbb-amq-0:8161
INFO[14:13:58] Port-Forward:       127.1.27.1 sbb-amq:61616 to pod sbb-amq-0:61616 
INFO[14:13:58] Port-Forward:       127.1.27.7 idm:9006 to pod idm-0:9006 
INFO[14:13:58] Port-Forward:       127.1.27.7 idm:80 to pod idm-0:9006 
ERRO[14:14:01] ForwardPorts error: unable to listen on any of the requested ports: [{80 9006}]** 

I got an error in the last line of the log, so I have realized that all the hostnames related to ports 80 and 9006 were not attached to the IP, which means:

- http://idm:9006 **doesn't work**
- http://127.1.27.7:9006 **works**

However:
- http://sbb-amq:8161 **works** as well (not using the port 9006)

Has anyone seen this before?

**EDIT:** I am using Ubuntu and the ports 80/9006 are not in use.

**Comment by cjimti** [comment]
@kelciocajueiro if the hostname `idm` points to IP `127.1.27.7` then calls to `http://idm:9006/` and `http://127.1.27.7:9006/` should work exactly the same on your computer since you are essentially always calling an IP. Your OS looks up the DNS before it makes a network connection. Some services that use HTTP may restrict access based on the hostname your browser or client sends as part of the request. 

I am going to close since it does not appear to be an issue with `kubefwd`, especially since calls to `http://127.1.27.7:9006/` is working for you, which means the forward itself is working.
