### ISSUE TITLE
Support multiple namespaces?

### ISSUE THREAD

**Issue by tmc** [txn2/kubefwd#4]
${servicename}.${namespacename} ?

**Comment by cjimti** [comment]
I think this would require a fairly explicit option since it would not be compatible with the main use case. 

Take for example:
127.1.27.10 auth-api auth-api.the-project.svc.cluster.local

Would not work with other namespaces that have a service called elasticsearch. If I append the namespace to the hostname as it looks like you are suggesting then it would not be consistent with how it is found in the cluster.

127.1.27.10 auth-api.the-project auth-api.the-project.svc.cluster.local

So http://auth-api.the-project would respond locally but the same call would fail from within the cluster. When building services that look for something like auth-api:80 they should find it as they would running in the namespace on the cluster.

I am open to suggestions or and PRs, however, I would like to maintain the original use case as well. One idea would be to have the main namespace "-n the-project"  then allow a list of additional namespaces, the additional namespaces would only get the full domain path.

127.1.27.10 auth-api auth-api.the-project.svc.cluster.local
127.1.27.11 auth-api.another-namespace.svc.cluster.local
127.1.27.11 something.another-namespace.svc.cluster.local

This would allow multiple namespaces to be forwarded, however you a running from the perspective of a particular namespace, like the-project in my example above.

Thoughts?

**Comment by cjimti** [comment]
Correct it's the opposite I would have trouble with. You may have services that communicate to services like http://elasticsearch:9200 in multiple namespaces as I do. So if I do not DNS the simple hostname "elasticsearch" for instance then I lose that ability locally and if I do forward it I risk collisions.

**Comment by tmc** [comment]
Oh right. I meant only do the short names for the primary namespace.

**Comment by cjimti** [comment]
Sounds good I'll do both for the primary, and any secondary would have to be accessed by ${namespacename}.svc.cluster.local. 

There are a couple of other features I would like to add so I created a milestone 1.4.

@tmc thanks for the feature request!

**Comment by cjimti** [comment]
@tmc version 1.4.0 now has multiple namespace support. 

**Example:**
`sudo kubefwd services -n primary-namespace -n other-namespace -n another-namespace`
