### ISSUE TITLE
support forward to service or pods optionaly

### ISSUE THREAD

**Issue by sgandon** [txn2/kubefwd#44]
This would be great that kubefwd support forwarding to native kubernetes services and not only to pods.
This could be done through an option of the commandline like
`sudo kubefwd svc`
`sudo kubefwd pod`

(thanks for this cool tool that really help developer smooth their test workflow)

**Comment by sgandon** [comment]
I would add this would also be grratly appreciated when doing some pod update using `helm upgrade` for instance cause new pods are created and old once deleted and the current behaviour (with forwarding to pods) stops working in the scenarion. The only way it to kill the command line and start it again.
If forward was done on the service this would not be required anymore :)

**Comment by sgandon** [comment]
It seems that the `kubectl port-forward svc/my-svc` is not forwarding to the service but to one single pod (very much alike kubefwd today) so I guess the go api shall also do the same. :sad:
https://github.com/kubernetes/kubernetes/issues/15180#issuecomment-457317821

**Comment by cjimti** [comment]
I'm going to close this for now since it's not feasible with the current Kubernetes API. I am hoping to have some time in the future to figure out a workaround. I would like to keep kubefwd a client-side only utility, however, to implement this may require the addition of temporary Pod as in internal proxy. This might be acceptable for some but could pose security problems and require additional privileges for some users. 

I'm going to mark this as "won't fix", however, it will remain on my radar. I am open to suggestions!

**Comment by hnicke** [comment]
My team suffers because of the same problem. A workaround could be to automatically reconnect upon failure. Could that be a solution?

**Comment by sgandon** [comment]
good idea.
