### ISSUE TITLE
Error running kubefwd as snap installation

### ISSUE THREAD

**Issue by mantzas** [txn2/kubefwd#46]
↳ sudo kubefwd svc -n default                                                                    
2019/03/13 11:36:28  _          _           __             _
2019/03/13 11:36:28 | | ___   _| |__   ___ / _|_      ____| |
2019/03/13 11:36:28 | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
2019/03/13 11:36:28 |   <| |_| | |_) |  __/  _|\ V  V / (_| |
2019/03/13 11:36:28 |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
2019/03/13 11:36:28 
2019/03/13 11:36:28 Version 1.7.3
2019/03/13 11:36:28 https://github.com/txn2/kubefwd
2019/03/13 11:36:28 
2019/03/13 11:36:28 Press [Ctrl-C] to stop forwarding.
2019/03/13 11:36:28 'cat /etc/hosts' to see all host entries.
2019/03/13 11:36:28 Loaded hosts file /etc/hosts
2019/03/13 11:36:28 Hostfile management: Backing up your original hosts file /etc/hosts to /root/snap/kubefwd/5/hosts.original
2019/03/13 11:36:28 Error reading configuration configuration: open /root/snap/kubefwd/5/.kube/config: no such file or directory

**Comment by cjimti** [comment]
@mantzas I have removed kubefwd from the snap store. Unfortunately, after many days of back and forth with the security team, they will not allow classic confinement. I was directed to use plug interfaces such as "network-bind" and "personal-files", however when I do it triggers a manual review. My latest response from them what that I don't need to explicitly ask for write permission to /etc/hosts
which is odd because when I turn that off I get permission denied. 

@mantzas thank you for reporting this and I am sorry if it wasted any of your time. I really hope you are able to benefit from kubefwd with an alternative method of installation.

I am going to close that as won't fix unless anyone has experience packaging this type of app for the snap store.
