### ISSUE TITLE
fails with index out of range [0] with length 0 error on v1.11

### ISSUE THREAD

**Issue by YashGajera** [txn2/kubefwd#99]
os: osx mojave

getting the following error on v1.11
`E1203 12:03:53.076848   63501 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 23 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x20e8960, 0xc0006dc860)
        /Users/cjimti/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191108065633-c18f71bf2947/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/cjimti/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191108065633-c18f71bf2947/pkg/util/runtime/runtime.go:48 +0x82
panic(0x20e8960, 0xc0006dc860)
        /usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/txn2/kubefwd/cmd/kubefwd/services.(*FwdServiceOpts).ForwardFirstPodInService(...)
        /Users/cjimti/workspace/txn2/kubefwd/cmd/kubefwd/services/services.go:477
github.com/txn2/kubefwd/cmd/kubefwd/services.(*FwdServiceOpts).ForwardService(0xc0000211d0, 0xc000461c18, 0x5, 0xc000461c10, 0x7)
        /Users/cjimti/workspace/txn2/kubefwd/cmd/kubefwd/services/services.go:351 +0x770
github.com/txn2/kubefwd/cmd/kubefwd/services.(*FwdServiceOpts).AddServiceHandler(0xc0000211d0, 0x219ea60, 0xc0008be1f8)
        /Users/cjimti/workspace/txn2/kubefwd/cmd/kubefwd/services/services.go:293 +0x198
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /Users/cjimti/go/pkg/mod/k8s.io/client-go@v0.0.0-20191108070106-f8f007fd456c/tools/cache/controller.go:198
k8s.io/client-go/tools/cache.newInformer.func1(0x2033620, 0xc0004c6b40, 0x1, 0xc0004c6b40)
        /Users/cjimti/go/pkg/mod/k8s.io/client-go@v0.0.0-20191108070106-f8f007fd456c/tools/cache/controller.go:370 +0x1b6
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000392000, 0xc0004f80f0, 0x0, 0x0, 0x0, 0x0)
        /Users/cjimti/go/pkg/mod/k8s.io/client-go@v0.0.0-20191108070106-f8f007fd456c/tools/cache/delta_fifo.go:422 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc0003ac000)
        /Users/cjimti/go/pkg/mod/k8s.io/client-go@v0.0.0-20191108070106-f8f007fd456c/tools/cache/controller.go:153 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004defb0)
        /Users/cjimti/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191108065633-c18f71bf2947/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00061ffb0, 0x3b9aca00, 0x0, 0xc000378001, 0xc0003da000)
        /Users/cjimti/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191108065633-c18f71bf2947/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /Users/cjimti/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191108065633-c18f71bf2947/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc0003ac000, 0xc0003da000)
        /Users/cjimti/go/pkg/mod/k8s.io/client-go@v0.0.0-20191108070106-f8f007fd456c/tools/cache/controller.go:125 +0x2fd
created by github.com/txn2/kubefwd/cmd/kubefwd/services.(*FwdServiceOpts).StartListen
        /Users/cjimti/workspace/txn2/kubefwd/cmd/kubefwd/services/services.go:275 +0x28b`

forwarding works fine in v1.10
workaround: downgrade to v1.10

**Comment by calmkart** [comment]
i have checked the code, the only different between v1.11.0 & v1.10.0 for this error is 
v1.10.x
https://github.com/txn2/kubefwd/blob/85038822ab5c9679c79cd5df3b68327cd73edeaa/cmd/kubefwd/services/services.go#L282-L302
https://github.com/txn2/kubefwd/blob/85038822ab5c9679c79cd5df3b68327cd73edeaa/cmd/kubefwd/services/services.go#L400

v1.11.x
https://github.com/txn2/kubefwd/blob/3e5aa5848ffe8d4abbc864c4a7f61272a43be697/cmd/kubefwd/services/services.go#L334-L344
https://github.com/txn2/kubefwd/blob/3e5aa5848ffe8d4abbc864c4a7f61272a43be697/cmd/kubefwd/services/services.go#L477

you can see we deleted the 
https://github.com/txn2/kubefwd/blob/85038822ab5c9679c79cd5df3b68327cd73edeaa/cmd/kubefwd/services/services.go#L296-L302
and change `pods.Items[:1]` to `[]v1.Pod{pods.Items[0]}`


because i think a repeated checks are not necessary.
but maybe some errors are triggered here. Need to check here again. I'm not sure.

when you use v1.10.0, Is there such output in your terminal like 
`log.Warnf("WARNING: No Running Pods returned for service %s in %s on cluster %s.\n", svc.Name, svc.Namespace, svc.ClusterName)`?

could you give more info here? and i'll fixed it. thanks.
@YashGajera

**Comment by YashGajera** [comment]
@calmkart yes, some of the services are scale down to 0 in the namespace and I'm getting a warning (eg `No Running Pods returned for service`) message in v1.10.0.

**Comment by calmkart** [comment]
@YashGajera 
ok, i'll fix this bug next day.

**Comment by YashGajera** [comment]
@calmkart Thank you

**Comment by calmkart** [comment]
fixed in #100
